### ISSUE TITLE
Database Permissions are not properly set.

### ISSUE THREAD

**Issue by YuxiXie** [WING-NUS/SSID#104]
All courses can be seen as admins (so far we can only create admin accounts). It'd be better to create TA accounts that can only access their own course.

**Comment by nguyen-mai-huong** [comment]
@YuxiXie Thank you for your feedback. The feature is deployed to SSID. Please help verify and close this issue.

@knmnyn @YuxiXie @YisongMiao @xiaowudeshen 
SSID admin user is now capable of creating new course and new teaching staff account. The teaching staff account can create TA accounts. Staff, and TAs will be able to access their own courses.

**Comment by nguyen-mai-huong** [comment]
I attached the screenshots below.

Logged in as an admin.

![Screenshot from 2022-03-24 17-31-39](https://user-images.githubusercontent.com/5399322/159886907-f1dc14a3-80b4-4bfd-98bc-1dfc43324443.png)

Create a new course.

![Screenshot from 2022-03-24 17-32-04](https://user-images.githubusercontent.com/5399322/159887058-bbf3980e-86df-4fb0-9f47-c9b958d79818.png)

Adding a teaching staff in the new course

![Screenshot from 2022-03-24 17-32-40](https://user-images.githubusercontent.com/5399322/159887194-bed5bb21-643d-4903-87ba-233d9d08550c.png)

Logged out, and logged in again as the teaching staff

![Screenshot from 2022-03-24 17-33-07](https://user-images.githubusercontent.com/5399322/159887292-23caae46-bd30-40d9-9fae-dc55925db99b.png)

Adding a TA

![Screenshot from 2022-03-24 17-33-28](https://user-images.githubusercontent.com/5399322/159887345-8c7ae67a-ddf7-4545-aee0-f2c0325e70f8.png)

The course after adding 2 users

![Screenshot from 2022-03-24 17-33-31](https://user-images.githubusercontent.com/5399322/159887432-7acd89ea-f44b-406d-9899-47d931d3338a.png)
