### ISSUE TITLE
Skeleton code being included in submission similarity result

### ISSUE THREAD

**Issue by nguyen-mai-huong** [WING-NUS/SSID#119]

**Comment by nguyen-mai-huong** [comment]
deployed to SSID 

![image](https://user-images.githubusercontent.com/5399322/161419911-a0bdf1b6-f790-4275-a73c-deecc021f85f.png)

will create a new issue and make link if there's further enhancement.

**Comment by knmnyn** [comment]
Nicely done!

**Comment by knmnyn** [comment]
Please add screenshot to the documentation for skeleton code.
