### ISSUE TITLE
Create signup page

### ISSUE THREAD

**Issue by nguyen-mai-huong** [WING-NUS/SSID#127]
Part of issue #86

**Comment by huyuxin0429** [comment]
Hey there, is this issue still open and available? I would like to work on this!

**Comment by nguyen-mai-huong** [comment]
Deployed to SSID. :yellow_heart: :tada:

**Comment by nguyen-mai-huong** [comment]
![signup-01](https://user-images.githubusercontent.com/5399322/200258129-9ff6fe2a-2a04-47a2-9ab2-3d692efdd1f9.png)

![activation-email](https://user-images.githubusercontent.com/5399322/200258155-50ab02b6-561f-4f14-a819-f573a508dc19.png)

![signup-02](https://user-images.githubusercontent.com/5399322/200258243-55ddab38-be89-491e-8844-ad55fdacf46e.png)

![user-can-sign-in-email](https://user-images.githubusercontent.com/5399322/200258307-a094e449-b4ef-4561-a771-aff909e7c0b5.png)

![signup-03](https://user-images.githubusercontent.com/5399322/200258326-e4dea658-c989-47cb-aaa0-312e15bb9480.png)
