### ISSUE TITLE
Include percentage value beside submission cluster's lines

### ISSUE THREAD

**Issue by eugenehuangsg** [WING-NUS/SSID#14]
A colour chart does helps to differentiate the percentage value but it is not a clear distinction. Having a percentage value beside the line would clearly allow evaluators to make the distinction.

**Comment by Riyas97** [comment]
We need to display exact percentage values for submission cluster. When we have too many students, advisable to keep the size between 3 and 10 users.

**Comment by Riyas97** [comment]
PR for this has been approved and merged. Hence closing this issue.
