### ISSUE TITLE
Deleting a guest user

### ISSUE THREAD

**Issue by huyuxin0429** [WING-NUS/SSID#178]
Currently, deleting a guest user throws an error. It will be better if we redirect to the course users page in this scenario.

![image](https://user-images.githubusercontent.com/24633766/174774681-f4f7e695-fc73-45d0-81a2-e146e981c62b.png)
![image](https://user-images.githubusercontent.com/24633766/174774753-48512306-4db5-4473-8f27-814b32772ff4.png)

**Comment by nguyen-mai-huong** [comment]
As of v.0.0.2, this issue is resolved.
