### ISSUE TITLE
User(admin and non admin) controllers require refactoring

### ISSUE THREAD

**Issue by huyuxin0429** [WING-NUS/SSID#202]
User controllers for admin and non-admin controllers use non-rails conventional methods to function. This is unnecessary and results in confusion.

**Comment by nguyen-mai-huong** [comment]
PR #269

**Comment by nguyen-mai-huong** [comment]
We rectified this issue during implementing PR https://github.com/WING-NUS/SSID/pull/274, and the change was deployed to production.
