### ISSUE TITLE
Change email validator to Rails email regrex

### ISSUE THREAD

**Issue by huyuxin0429** [WING-NUS/SSID#215]
This improves the readability of the email validation code and help conform to a standardized method

**Comment by nguyen-mai-huong** [comment]
@knmnyn The Rails email regex is a bit too broad e.g. it allows 123@123. I think it's probably not good for us to follow the Rails convention in this case.

**Comment by knmnyn** [comment]
Ok, then do as you see fit! :D. Thank you
