### ISSUE TITLE
Migrate user authentication and authorization system to devise

### ISSUE THREAD

**Issue by huyuxin0429** [WING-NUS/SSID#238]
The current system used is manually implemented and does not make full use of currently available user authentication and authorization system libraries (Eg. Devise).

Benefits: less clunky and error-prone user management code. More extensible with pre-written extensions available for libraries (Eg. Google SSO_

**Comment by nguyen-mai-huong** [comment]
PR #274

**Comment by nguyen-mai-huong** [comment]
We rectified this issue during implementing PR https://github.com/WING-NUS/SSID/pull/274, and the change was deployed to production.
