### ISSUE TITLE
Unable to login with admin account in localhost due to inconsistency between schema.rb and seeds.rb

### ISSUE THREAD

**Issue by florentianayuwono** [WING-NUS/SSID#298]
On `schema.rb`, the `users` table is created with fields as follow:
<img width="631" alt="image" src="https://github.com/WING-NUS/SSID/assets/76247368/7f241df8-ac2f-488b-aab4-e3cc7700d983">

However on `seeds.rb`, the `users` table is populated with the following data:
<img width="368" alt="image" src="https://github.com/WING-NUS/SSID/assets/76247368/a203407a-a30f-4981-b1d7-f94156af6776">

For context, the `seeds.rb` used to be this:
<img width="353" alt="image" src="https://github.com/WING-NUS/SSID/assets/76247368/cf636a37-fe28-4916-ab51-368d27a3b4a0">

Upon trial on the login page:
1. Entering  with password 'SSIDPassword' will lead to an "Invalid user/password combination" error, which means the `seeds.rb` data cannot be populated into the `users` table.
2. Entering with password '$$SSIDPassword$$' will lead to "Your account is not activated" error. My guess is the default "encrypted_password" on `schema.rb` is based on the digest of '$$SSIDPassword$$', hence it pass the `valid_password` condition.

![photo_6293965992228927298_y](https://github.com/WING-NUS/SSID/assets/76247368/f804fb90-9120-488c-9ce7-6dc6f8f0ada7)

**Comment by huyuxin0429** [comment]
Good catch, try to submit a PR for the fix

Potential resource:
https://stackoverflow.com/questions/12418584/seeding-users-with-devise-in-ruby-on-rails
