### ISSUE TITLE
Allow preview of submissions during upload phase

### ISSUE THREAD

**Issue by eugenehuangsg** [WING-NUS/SSID#32]

**Comment by nguyen-mai-huong** [comment]
@sibinhho99 Yay, deployed to SSID. :smiling_face_with_three_hearts:

![preview-upload-01](https://user-images.githubusercontent.com/5399322/183051245-57f59dcc-62ba-4634-830d-b2480fa24c8d.png)

![preview-upload-02](https://user-images.githubusercontent.com/5399322/183051276-7fd223db-dfd1-4a82-bb87-867032ef67fa.png)
