### ISSUE TITLE
Data too long for column 'upload_log' at row 1 

### ISSUE THREAD

**Issue by Riyas97** [WING-NUS/SSID#39]
![Data_too_long_for_column](https://user-images.githubusercontent.com/42403047/92260616-c4483780-ef0a-11ea-930a-59160eecf1ba.png)

When does it occur?
It occurs after one have submitted assignment for plagiarism detection.

Why does it occur?
It seems to occur because the data to be inserted for a column exceeds that of its capability to store that data.

**Comment by Riyas97** [comment]
After more debug, I realised this error is more likely to happen when a developer adds in more console messages under upload_log especially during testing or debugging errors. Our current column type is `text` which can take up around 65,535 characters. As much as I have tested, our current column capability does not pose any issues for up to 500 uploaded student works for a particular assignment. Hence, @knmnyn Please advise whether do you want me to change the text type to something that can hold more characters like LONGTEXT or just leave it like this and instead just add a note for developers that when they add more console messages under upload_log, they can encounter this error and during those times, they have to manually change the text type? Thanks a lot.

**Comment by knmnyn** [comment]
@Riyas97 We should truncate any messages longer than the MAX_LENGTH for the field and `alert` the developer that the field may be truncated.  Do they see this data anywhere in the UI?
