### ISSUE TITLE
App sending a NaN value to database

### ISSUE THREAD

**Issue by Riyas97** [WING-NUS/SSID#40]
![undefined column](https://user-images.githubusercontent.com/42403047/92304590-f5c80e00-efb1-11ea-99db-6bcea2512920.png)

Currently, the app is unable to ignore empty files (files which do not contain anything at all). As such, when these empty files are compared with other files for signs of plagiarism, the computed plagiarism rate for these files becomes an undefined value as shown below where the denominator is 0 for files which do not have any content:

![Undefined Value](https://user-images.githubusercontent.com/42403047/92304670-9f0f0400-efb2-11ea-90b6-6c6b296d43c4.png)

**Comment by Riyas97** [comment]
So, I suggest we ignore these files in our plagiarism check since they don't have any code to check for plagiarism as well.

**Comment by knmnyn** [comment]
Sounds good.  Please go ahead with this

**Comment by knmnyn** [comment]
Hi @Riyas97 is this issue resolved?  If so you can close a few of these down and let them pop up again if needed.
