### ISSUE TITLE
Anonymiser script.

### ISSUE THREAD

**Issue by knmnyn** [WING-NUS/SSID#42]
Take code and run to check for global IDs, email addresses and webpages, and other handles (github ID, twitter, etc.) and change these IDs through a one-way hash function to output a new file that preserves everything else.

Flag the new output as having been produced by the script.

Flags possible IDs information that is not programmatically recognizable (e.g., names):

Author .... <- flag this as possible student ID
L xx has "Author ...." you may want to manually change this to "Author xxxx"

Output all changed lines to Stderr with their original.

Cross Reference #33.

**Comment by Riyas97** [comment]
PR for this has been approved and merged. Hence, closing this issue.
