### ISSUE TITLE
Obfuscated public link for login or for visualization of submissions

### ISSUE THREAD

**Issue by knmnyn** [WING-NUS/SSID#43]
To allow TAs to review without needing login or credentials.

**Comment by knmnyn** [comment]
That will be great because at 860 students, I don't think one person can review all the results.  Another possibility is to allow for a user to invite other user to view the results.  Then we can be sure that whoever has access to it is authorised.

**Comment by knmnyn** [comment]
Need a tutorial for this functionality when we know it is properly working.  See Jon or Eugene's thesis work.

**Comment by knmnyn** [comment]
Set it to a month by default.  Allow destroy and recreate.

**Comment by Riyas97** [comment]
PR for this has been approved and merged. Hence, closing this issue.
