### ISSUE TITLE
One Zip File Problem (When each student only have one file to submit?)

### ISSUE THREAD

**Issue by xiaowudeshen** [WING-NUS/SSID#68]
For the situation that each student is only require to submit one file for their submission, can we just put all of the files into a single folder and zip it? 

When the SSID detect that the zipped file only contain one folder, can we just do the comparison between each others instead of checking for all the folders of different students. 

Currently, this job is done by creating one folder for each assignment file and can we simplify this process?

**Comment by YuxiXie** [comment]
Yes, it still works when putting all of the files into a single folder and zip it.
