### ISSUE TITLE
Review beginner version of SSID README

### ISSUE THREAD

**Issue by YisongMiao** [WING-NUS/SSID#70]
Hi team:

We need to review the beginner version of SSID README: https://github.com/WING-NUS/SSID/blob/master/README-v-Beginner.md

**Comment by YisongMiao** [comment]
Victor? I cannot find you @xiaowudeshen

**Comment by knmnyn** [comment]
Added @xiaowudeshen to the WING NUS member list.

**Comment by xiaowudeshen** [comment]
Hi, for this one, I updated a bit on how to install the ruby and bundler of the correct version, pls verify through https://github.com/WING-NUS/SSID/pull/84

**Comment by YisongMiao** [comment]
Verified Victor's update, issue close.

**Comment by knmnyn** [comment]
Post-edited as well.   LGTM.
