### ISSUE TITLE
Documentation for semestral clearing of courses and submissions

### ISSUE THREAD

**Issue by knmnyn** [WING-NUS/SSID#90]
Documentation and/or rake commands to archive and export non-necessary data from SSID for preparing for next semester.

**Comment by nguyen-mai-huong** [comment]
@knmnyn : I've archived the previous assignments. Exporting them is still in progress.
SSID is in a clean state, and instructors can only access their own courses.

![Screenshot from 2022-05-31 15-08-17](https://user-images.githubusercontent.com/5399322/171118294-19023ea8-3fd8-467b-8f0b-e5f31b8072c7.png)

@YisongMiao @xiaowudeshen @YuxiXie : please create teaching staff users upon creating courses. 

![image](https://user-images.githubusercontent.com/5399322/171118673-4e1510ad-c68d-46f6-bb04-2e94b88de9a5.png)

**Comment by knmnyn** [comment]
Noted with thanks.  Please document the semestral archiving style somewhere and save the archives in an appropriate storage place.  We will figure out a good long-term solution to this, as there are good use cases where past semester's submissions from students of a particular course may still be required to check for plagiarism in the current cohort (e.g., especially when an assignment is used from a past year; where juniors get a model solution from a senior)
